sudo: required
language: generic
services:
  - docker
env:
  global:
    - DOCKER="sfalexrog/gitbook-builder"
git:
  depth: 1
before_script:
  - docker pull ${DOCKER}
script:
  - docker run --rm -v $(pwd):/gitbook ${DOCKER}
deploy:
  provider: pages
  local-dir: _book
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: master
  on:
    branch: master-docs
